spring.application.name=agent
#spring.ai.deepseek.api-key=sk-eb0a6cb0568a490f824fd5d4eb156e9d
#spring.ai.deepseek.chat.options.model=deepseek-coder

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3

#to start ollama: ollama run llama3
#to stop lollama: taskkill /F /IM ollama.exe